### ISSUE TITLE
Not working with multiple devices

### ISSUE THREAD

**Issue by ErnestStaug** [mauro-midolo/homeassistant_electrolux_status#1]
I've added integration, after adding credentials I get this 
`2022-03-04 22:55:34 WARNING (MainThread) [homeassistant.config_entries] Config entry 'e*****@gmail.com' for electrolux_status integration not ready yet; Retrying in background`

<img width="297" alt="image" src="https://user-images.githubusercontent.com/17262977/156845932-a09d6e4a-6e0d-4366-9435-f5bd4cdb265a.png">

**Home Assistant version 2022.3.0**

nothing happens, I've  tried reinstalling it.

Seems like there is issue with IDs? 

<img width="687" alt="image" src="https://user-images.githubusercontent.com/17262977/156846275-c8f54ede-b2ee-4310-8c7e-3f3154bedc5d.png">

**Comment by mauro-midolo** [comment]
CIao @ErnestStaug,
Did you set an Alias to your appliance into the Electrolux app?

**Comment by SiM22** [comment]
So I initially thought it was not working either. I have an AEG 6000 Series Washing Machine, I had installed this add-on before adding the appliance to the Electrolux/AEG care app and naming it as specified in the Readme. It did not show up in Home Assistant.

You have to follow these steps.

1. Add device to AEG/Electrolux Care App (iOS/Android)
2. Name the device in the app as My Electrolux Care
3. Go to HACS and install the add-on
4. Go to Home Assistant and add the Electrolux Integration
5. Log in with your account and device should appear

**Comment by ErnestStaug** [comment]
![4980F036-AA3D-47E9-A044-DC6B75F005A1](https://user-images.githubusercontent.com/17262977/157286291-b53296c9-a945-40f2-b685-55086d5cfb7b.png)
![436E10EF-A9E8-4732-A2B5-AA979F6BFBD4](https://user-images.githubusercontent.com/17262977/157286299-a788a6e1-f162-487f-a715-7c39f78df929.png)
 they are named.

**Comment by SiM22** [comment]
They are named incorrectly. The device should be named "My Electrolux Care"

You have different names that what the instructions state. Change the name and it should work

**Comment by SiM22** [comment]
Yes

**Comment by tomeko12** [comment]
>They are named incorrectly. The device should be named "My Electrolux Care"

I think, it's not a problem.
@ErnestStaug, do You have registered two Electrolux/AEG appliances? If yes, there's probably a problem with multiple devices registered in account (inside my library, or @mauro-midolo integration)

**Comment by ErnestStaug** [comment]
> > They are named incorrectly. The device should be named "My Electrolux Care"
> 
> I think, it's not a problem. @ErnestStaug, do You have registered two Electrolux/AEG appliances? If yes, there's probably a problem with multiple devices registered in account (inside my library, or @mauro-midolo integration)

Yes there is two separate apps and two appliaces, cooker and a washing machine/dryer.

**Comment by ErnestStaug** [comment]
> They are named incorrectly. The device should be named "My Electrolux Care"
> 
> You have different names that what the instructions state. Change the name and it should work

Your suggestion does not work either as I am not able to rename it :) 
![2E0200F3-E9A2-48E5-99FB-8DAF2D98754E](https://user-images.githubusercontent.com/17262977/158464715-1f169775-e046-4b86-b1eb-7ce199659870.png)

**Comment by mauro-midolo** [comment]
Ciao @ErnestStaug,
There are not named restriction.
And i testested the multiple instances, its works corretly.
I don't undestand which Is the problem in your case.
Could you please give us more informations in order to undestand better your configuration.
Thanks

**Comment by ErnestStaug** [comment]
> > They are named incorrectly. The device should be named "My Electrolux Care"
> 
> I think, it's not a problem. @ErnestStaug, do You have registered two Electrolux/AEG appliances? If yes, there's probably a problem with multiple devices registered in account (inside my library, or @mauro-midolo integration)

I can confirm, it works when I remove `oven` from AEG Kitchen app. So leaving one device seems to solve the issue, but I sill need support for multiple devices.

**Comment by tomeko12** [comment]
@mauro-midolo, have You tested with one instance and multiple devices registered on one account? In EMEA region, there's multiple apps (Electrolux/AEG Care/Kitchen) that use one account to register multiple appliances (washing machines and ovens).

**Comment by jbergler** [comment]
There's not enough info in this thread for me to say for sure if this is related, but I had an issue with multiple devices because some devices don't appear to have a model number returned from the server. I've fixed this for me in #4, maybe it helps with this problem too.

**Comment by mauro-midolo** [comment]
Ciao @ErnestStaug,
I release a new version with some fix about model appliance did by @jbergler 
Could you please try v1.6.0 version?

Thank you

**Comment by tomeko12** [comment]
Maybe #10 repair this issue.

**Comment by ErnestStaug** [comment]
Latest update v1.9 
<img width="942" alt="image" src="https://user-images.githubusercontent.com/17262977/159774696-17e583ab-286a-45c5-9b74-f16c2f1214d7.png">
 Still persists... 
 
 P.S. The older configuration (where I only had one device) seems to work.

**Comment by tomeko12** [comment]
@ErnestStaug , could You test this code (with two appliances):
```python
import pyelectroluxconnect
ses = pyelectroluxconnect.Session("emailaddress", "password",  raw = True, verifySsl = True, region="emea")
ses.login()
appllist = ses.getAppliances()
print(appllist)
for appliance in appllist:
    print("-------------------------------------------------------------------------------------------")
    print(ses.getApplianceProfile(appliance))
    print("-------------------------------------------------------------------------------------------")
    print(ses.getApplianceState(appliance, rawOutput = False))
```
and paste output?

**Comment by ErnestStaug** [comment]
Yes, sur
[out2.txt](https://github.com/mauro-midolo/homeassistant_electrolux_status/files/8335977/out2.txt)
e

**Comment by ErnestStaug** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/17262977/159889656-4023254a-4d2b-4f30-acb3-dc6f5829476a.png">
All good now! Thank you!
