### ISSUE TITLE
Sensor naming problems 

### ISSUE THREAD

**Issue by dikkeleo2** [mauro-midolo/homeassistant_electrolux_status#102]
After the update to 2.8.1 the connection with aeg is working again. Thanks!

However there is an issue with the naming of the sensors/parameters.

![Screenshot_20230518-154421](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/5685519/e4ddf49c-608c-45ce-a435-4c53b22ee58b)

**Comment by mauro-midolo** [comment]
This is the same problem of #108,
Please update to v2.8.2
