### ISSUE TITLE
Username/Password is wrong - AEG L8FQS967C2

### ISSUE THREAD

**Issue by jbrandt004** [mauro-midolo/homeassistant_electrolux_status#106]
I am trying to connect the washing machine AEG 8000 ØkoMix Autodose 9kg to the integration. I have double and tripple checked all details when filling in the form, but I keep getting the same error message.

Is this washing machine supported, or is the error message due to an unsupported washing machine?

Thanks

**Comment by flbre** [comment]
I have the same problem i has been using this i for a year but after last update it say wrong password or user,

**Comment by Enough64** [comment]
Same here

**Comment by flankoBlanko** [comment]
Same here

**Comment by IAmVespa** [comment]
Same for me. Electrolux Dryer EW9H283BY

**Comment by mauro-midolo** [comment]
Do you have the last version v2.8.2?

**Comment by jdpiguet** [comment]
How can I find the version?

**Comment by flbre** [comment]
perfect after the upgrade to 2.8.2 it's work for me

**Comment by flbre** [comment]
> How can I find the version?

Hi jdpiguet you can upgrade it under your HACS

**Comment by flankoBlanko** [comment]
My bad... I wasn't on latest version of home assistant core and HACS wasn't showing the update of Electrolux. Once updated the core, the update showed up in HACS. After updating Electrolux to latest 2.8.2 is working! Thanks

**Comment by IAmVespa** [comment]
Sorry, same problem as @flankoBlanko 
I had HA version 2023.5.2 while the 2023.5.4 was needed to see the latest 2.8.2  Electrolux version.
Now everything is fine.
