### ISSUE TITLE
Could not log in to ElectroluxStatus, Invalid API response: Unauthorized (401)

### ISSUE THREAD

**Issue by cloudbr34k84** [mauro-midolo/homeassistant_electrolux_status#110]
Just saw im getting this error. Im also trying to log into the app and that does not seem to be working as well

```
Logger: custom_components.electrolux_status
Source: custom_components/electrolux_status/__init__.py:51
Integration: Electrolux Care Integration ([documentation](https://github.com/mauro-midolo/homeassistant_electrolux_status), [issues](https://github.com/mauro-midolo/homeassistant_electrolux_status/issues))
First occurred: 9:25:47 pm (2 occurrences)
Last logged: 9:28:51 pm

Could not log in to ElectroluxStatus, Invalid API response: Unauthorized (401)
```
```
Logger: homeassistant.config_entries
Source: config_entries.py:1247
First occurred: 9:28:51 pm (1 occurrences)
Last logged: 9:28:51 pm

Config entry 'Electrolux Fridge' for electrolux_status integration could not authenticate: None```

**Comment by mauro-midolo** [comment]
Please @cloudbr34k84, Update Home Assistant to 2023.5.3 and integration to v2.8.2.

**Comment by cloudbr34k84** [comment]
> Please @cloudbr34k84, Update Home Assistant to 2023.5.3 and integration to v2.8.2.

Thanks,  I have upgraded but when I go to add my username and password it's saying they are wrong even though I just used them to log into the app 🤔

**Comment by cloudbr34k84** [comment]
I checked logs

Logger: custom_components.electrolux_status.config_flow
Source: custom_components/electrolux_status/config_flow.py:126
Integration: Electrolux Care Integration (documentation, issues)
First occurred: 5:50:27 am (4 occurrences)
Last logged: 7:49:35 am

Invalid API response: Unauthorized (401)
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/config_flow.py", line 126, in _test_credentials
    await self.hass.async_add_executor_job(client.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 1073, in login
    raise Exception(ErrorArg) from None
Exception: Invalid API response: Unauthorized (401)

Fridge is connected as per prequistes 

![Screenshot_20230531-075018.png](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/58960644/29a447c7-ab68-4d1f-af5d-1af688fe52d6)

**Comment by cloudbr34k84** [comment]
Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:213
First occurred: 5:50:27 am (5 occurrences)
Last logged: 7:49:35 am

Exception in _getAppliancesList: Invalid API response: Unauthorized (401)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 188, in _getAppliancesList
    _json = self._requestApi(urls.getAppliances(self._username))
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 980, in _requestApi
    raise ResponseError(errcode, message) from None
pyelectroluxconnect.Session.ResponseError: Invalid API response: Unauthorized (401)

**Comment by jbergler** [comment]
I think this is the same problem as previously, I filed a ticket upstream: https://github.com/tomeko12/pyelectroluxconnect/issues/12

**Comment by mauro-midolo** [comment]
Please, upgrade to v2.10.0

**Comment by cloudbr34k84** [comment]
Back in business 👌👌
