### ISSUE TITLE
API changed?

### ISSUE THREAD

**Issue by Biyadh00** [mauro-midolo/homeassistant_electrolux_status#118]
Few hours ago, the integration stopped working.
I tried to delete it and add it again but always got "Username/Password is wrong."

**Comment by DragonQ** [comment]
Same here

**Comment by ArnoldVisser** [comment]
can you login to the phone app?

**Comment by Biyadh00** [comment]
> can you login to the phone app?

Yes. Phone app working.

**Comment by Biyadh00** [comment]
Working again.
