### ISSUE TITLE
Feature Request: Start time entity

### ISSUE THREAD

**Issue by schumi2004** [mauro-midolo/homeassistant_electrolux_status#119]
Hi,

Let me first say that this module is working perfect!
Since i implemented it i also wanted to make use of the timer-bar-card except i'm having some issues presenting the correct timings.
It looks like i'm missing the exact start time when a program is started on for example my wasching machine.
Would it be possible to add a start_time entitiy in this module?

More details regarding the timer-bar-card and my issue can be found here:
https://github.com/rianadon/timer-bar-card/issues/93

**Comment by mauro-midolo** [comment]
Hi @schumi2004 , 
all information is read from the Electrolux cloud platform automatically.
No additional information can be added as it is not provided by the source application.
