### ISSUE TITLE
Unable to add more than one user

### ISSUE THREAD

**Issue by hjaltij** [mauro-midolo/homeassistant_electrolux_status#125]
There seems to be a bug in the My Elecotrolux Care app where I'm unable to open the app after I've added an appliance. I've tried it multiple times but it just deadlocks on a spinner. This makes it impossible to add a second appliance (I have washer and dryer).

I "resolved" it by creating a new user for the second appliance and tried to add another entry in the integration. I soon realized that this wasn't supported so I checked the code and it looks like the same token file is always used regardless of configuration.

I made a quick change to the `pyelectroluxconnect_util.py` which fixes the issue but would break all existing configurations so it needs more work to be suitable as a patch.

I was fine with configuring both accounts again so this does it for me.

See diff below:

```
@@ -5,5 +5,5 @@ class pyelectroluxconnect_util:
     @staticmethod
     def get_session(username, password, region="emea", language ="eng"):
         return pyelectroluxconnect.Session(
-            username, password, deviceId="ElectroluxHomeAssistant", language=language, region=region,
+            username, password, deviceId="ElectroluxHomeAssistant", tokenFileName=username, language=language, region=region,
         )
```

**Comment by mauro-midolo** [comment]
Ciao @hjaltij, I have just released a new version, v3.0.0, incorporating your suggestion. I tested it with one account, and it didn't produce any blocks or breaking changes.

Could you please test this new version with 2 accounts?

**Comment by tieskuh** [comment]
This is a breaking change for me. 
After upgrading the integration said it needed to be reconfigured. I was unable to log in with my AEG credentials (username/password incorrect). I downgraded to the previous version and everything started working again without configuration.

**Comment by mauro-midolo** [comment]
@tieskuh please upgrade to v3.1.0

**Comment by tieskuh** [comment]
> @tieskuh please upgrade to v3.1.0

Seems to work after upgrading to 3.1.0. Thanks!
