### ISSUE TITLE
Status of the entities is fluctuating

### ISSUE THREAD

**Issue by micro521** [mauro-midolo/homeassistant_electrolux_status#126]
I have observed recently that the status of the entities from this integration are fluctuating.
For example the Appliance status is fluctuating between Off and CycleIsFinished. The period is not stable but usually 3-5 minutes.
I see similar fluctuation in most of the entities for the integration.
In the Electrolux app the machine looks to be offline. (It is offline actually.)
![appliance_status](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/95082251/b3f8d8fa-7b77-4aa5-a109-2f63d0f6ec8b)
Is this a general issue or just happens to me?

**Comment by ikbenfrank** [comment]
Same here with a washing machine. Started about 15 hours ago and has been offline the entire time. It's not fluctuating anymore for the last few hours but it's updating cycle is finished every few hours. It's not affecting everything but appliance status, door lock, cycle phases, temperature, tank reserve are among the fluctuations.

If I can do anything to help troubleshooting let me know.

**Comment by micro521** [comment]
It is not fluctuating in the last few hours. Probably it was an issue from Electrolux server's side. I will monitor further.

**Comment by mauro-midolo** [comment]
the information and values are read from the Electrolux servers, so this fluctuation is received directly from the servers.
It is not possible to solve the problem on the integration side.

**Comment by micro521** [comment]
Thanks for the feedback. I close the ticket.
