### ISSUE TITLE
LFR  73864OC can't login to my AEG account

### ISSUE THREAD

**Issue by montzcz** [mauro-midolo/homeassistant_electrolux_status#141]
Hello,
First of all - thanks for excellent job. Since version 3.1.0 (not very sure about the version when it has began) I can't login to my AEG account in your integration, all I got is "Username/Password is wrong." Before it worked flawlessly.
I checked many times that my login data are OK, they work well with mobile AEG app (on cell phone).
Any idea what could be wrong?¨Thanks.

**Comment by Staalrat** [comment]
Hi Mauro,

I have the same issue. Connection was successful for a few months and has now stopped working. Did a password reset to be sure and I can login to the AEG app but not into the integration with same credentials.

**Comment by Dejmal69** [comment]
Hello everyone. This problem has a solution.
Edit the pyelectroluxconnect version from 3.19 to 3.20 in the manifest file and restart HA

**Comment by montzcz** [comment]
Thank you!
M.
