### ISSUE TITLE
Username/Password is wrong

### ISSUE THREAD

**Issue by snp-g** [mauro-midolo/homeassistant_electrolux_status#148]
HI

I tiried two latest releases v4.1.0 and v4.0.0 as well as checked and created login on My Electrolux https://www.electrolux.cz/mypages/#MyProducts, since I initially register AEG washing machine with My AER Care application, so My Electrolux application can see the AEG washing machine too.

However even that I cannot log in wich failes with error Username/Password is wrong.

Here is the log form HA server. 

`2023-11-30 12:00:50.268 WARNING (SyncWorker_7) [pyelectroluxconnect.Session] Getting new auth token
2023-11-30 12:00:50.890 ERROR (SyncWorker_7) [pyelectroluxconnect.Session] Invalid username or password (AER0802)
2023-11-30 12:00:50.891 ERROR (MainThread) [custom_components.electrolux_status.config_flow] Invalid username or password (AER0802)
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/config_flow.py", line 126, in _test_credentials
    await self.hass.async_add_executor_job(client.login)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 1061, in login
    self._createToken()
  File "/config/deps/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 176, in _createToken
    raise LoginError(f'{err.message} ({err.status_code})') from None
pyelectroluxconnect.Session.LoginError: Invalid username or password (AER0802)`

Could you please help me?

**Comment by RLECGI** [comment]
Aha, so i am not the only one with issues. Mine does say user pass incorrect but i have dozens (50!?) of reconfigure messages on the integrations page. Reconfiguring them with the correct password says user pass incorrect.
![aeg](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/46313583/b6695546-9836-4c0e-bde1-8afed00c5db5)

**Comment by LordMike** [comment]
Sounds like the API is unstable - so maybe more retries are in order (perhaps with backoff)?

**Comment by AverageJoe89** [comment]
It is unstable, for me reconfiguration did not work, but reloading HA did.

**Comment by snp-g** [comment]
Well, I think we have different issues as I have never been able to configure my plugin.

I tried many times and it do not work yet.

Is there anything I can provide more or test, please?

**Comment by LordMike** [comment]
Sounds like the same issue - I mention retries because it seems like it works sometimes. So reconfiguring, reloading the plugin (restarting HA) etc - all achieve the same thing: trying again.

**Comment by LordMike** [comment]
I've looked at the code here and in the core library, and in both places there is _no_ retrying. I've made a [request here](https://github.com/tomeko12/pyelectroluxconnect/issues/19).

**Comment by hvinhtam** [comment]
hiện tại tôi không đăng nhập được nữa. toàn báo sai pass và user. xin giúp đỡ

**Comment by kovacsla** [comment]
I have same problem. The integration has unstable connection the last few days, but today completely missing it. I try reloading configuration, but doesn't work. I try to reconfiguration, but Username/Password is wrong. Same username and password working with Android app. 

Could anybody help me?

![Screenshot_20240119_144902_Electrolux](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/117943937/ca0c5508-0f68-4e26-8680-9391945fab6f)
![Képkivágás_Electrolux2](https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/117943937/9c75c5ee-b495-4964-a45f-4c7e69725daa)

**Comment by abdonkov** [comment]
Electrolux / AEG has ended support for the old apps and API, the pyelectroluxconnect library repo has been archived as it no longer works, so this integration won't work anymore as well.

So we will be waiting until someone makes an integration with the new API.

**Comment by mauro-midolo** [comment]
Please, refer to the ticket #159 for all the details regarding the disruption of integration caused by the change in Electrolux server APIs
