### ISSUE TITLE
Electrolux Life (APAC region) app no longer working, replaced with Electrolux app

### ISSUE THREAD

**Issue by allistermaguire** [mauro-midolo/homeassistant_electrolux_status#149]
More of an FYI. To use the new app you need to reset your account details and access to the Electrolux Connectivity Platform (ECP) stops. The 'Electrolux' app uses the Electrolux OCP API which as is in the readme, is not supported by this integration.

**Comment by haroldboom** [comment]
Hi so APAC region cant use this integration anymore? My account was moved to Electrolux app, my integration stropped working which prompted me to check the app which no longer works. Is there any alternative?

**Comment by cloudbr34k84** [comment]
Yep just found this out as well.

**Comment by henriec** [comment]
EMEA region here. also stopped working. We reveived an email from AEG stating the account has moved to the new app

**Comment by jyavenard** [comment]
Subscribing. Integration now always giving a username/password error when it’s definitely correct

**Comment by allistermaguire** [comment]
There is a bit of a discussion in the pyelectroluxconnect repo about supporting/moving to the new API, which this integration uses.

**Comment by jbergler** [comment]
@allistermaguire could you link to that discussion (I couldn't find it)

Also, can anyone confirm the error they see in home assistant logs? Is it this one?
```
pyelectroluxconnect.Session.LoginError: Cloudant error: Payment required (AER0802)
```

**Comment by allistermaguire** [comment]
@jbergler No problem, the title isn't what you would be looking for :) https://github.com/tomeko12/pyelectroluxconnect/issues/14

**Comment by tdsmtdsm** [comment]
Also encountered a forced migration from "AEG Kitchen" app to "AEG" app.
503/504 errors in the log.

**Comment by mauro-midolo** [comment]
Please, refer to the ticket #159 for all the details regarding the disruption of integration caused by the change in Electrolux server APIs
