### ISSUE TITLE
Feature request: start button for washing machine / dryer

### ISSUE THREAD

**Issue by Rikkie80** [mauro-midolo/homeassistant_electrolux_status#15]
This is already a great integration, but would be even better if I can remotely start my washing machine and dryer via an automation (e.g. with condition that my PV system generates enough power).

To be able to remote start the washing machine via the AEG app first some preconditions need to be met:
- delay start set
- start button pushed after setting up "delay start" (door will be locked)

My (working) appliances:
- Dryer: T9DENS87
- Washing Machine: l7FENQ96

**Comment by tomeko12** [comment]
Hi @Rikkie80 
Please, check new version: v1.12.0

**Comment by Rikkie80** [comment]
Thanks. Upgraded and the new buttons are working perfectly (ON button is a bit useless as the machines disconnect from WiFi when they're off)
