### ISSUE TITLE
Integration keeps creating new "instances"

### ISSUE THREAD

**Issue by sbayxx** [mauro-midolo/homeassistant_electrolux_status#153]
Hi - new instances keeps popping up in HA - see attached screenshot. How can i stop that from happening?
<img width="1208" alt="Screenshot 2024-01-09 at 08 54 22" src="https://github.com/mauro-midolo/homeassistant_electrolux_status/assets/147490484/d2bf7ad3-e18c-47f1-abd5-85c2417d34e1">

**Comment by VanFlipsen** [comment]
I the same issue. 

The original integration is in errorstate, remove the new instances. En reload the integration. Works for me. 

In the errorlog after a restart of HA error and "max retries exceded" a new instances is created.

**Comment by mauro-midolo** [comment]
Please, refer to the ticket #159 for all the details regarding the disruption of integration caused by the change in Electrolux server APIs
