### ISSUE TITLE
AGE kitchen is changed to new AEG app and can not authenticate

### ISSUE THREAD

**Issue by Arturasm** [mauro-midolo/homeassistant_electrolux_status#154]
Opening AEG kitchen I was asked to update to new app AEG. Then all authentication went ok in the app. But not integration.
EMEA region.

**Comment by wgumaa** [comment]
It is the same with Electrolux as well. Provide credentials but says Username/Password is wrong.

**Comment by daniel-toth-leeder** [comment]
I have the same issue. I've just installed v5.0.0 yesterday, all was fine.
Today I faced the same issue as described above.
The exception is that I've been using MyAEG app so far, and now I had to move to [AEG](https://apps.apple.com/gb/app/aeg/id1599494494).
Yesterday, the credentials worked, but today, the integration asked me to re-enter user/pass, and it failed, of course in the AEG mobile app all works well.

**Comment by SimonLeigh** [comment]
I too have this issue.

**Comment by wgumaa** [comment]
I rolled back to the previous version and it works.

**Comment by wgumaa** [comment]
now its stopped working. Anyone able to log in into the integration?

**Comment by slingshot74** [comment]
Same issue, no new app, but in HA it tells me to setup the integration again nut credentials are not accepted.

**Comment by mhaket** [comment]
I encounter the same problem. I can login into the AEG app, the MyAEG website but the same credentials do not work in this integration. Same error message

**Comment by Sroll5** [comment]
Hello, I'm in the same situation...the username and password are OK on the AEG web or in the mobile app, BUT the integration needs reconfigure in HA and the credentials doesn't works for EMEA :( Wrong password.  Could you please fix it for us? This integration is really great. The coffee wil surely arrive after fix...I swear ;-)

Core 2024.1.4
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

**Comment by slingshot74** [comment]
See the other issue / thread 
Electrolux / AEG has stopped the old API integration.

**Comment by Palmdale95** [comment]
Hi guys. I am also in the loop. No connection possible. Checked the credentials in the AEG app and it is working fine. In HA integration not possible. EMEA with English sensor names. Worked fine until today in the morning. After the HA core update I had to insert my credentials again and failed.

**Comment by mauro-midolo** [comment]
Please, refer to the ticket #159 for all the details regarding the disruption of integration caused by the change in Electrolux server APIs
