### ISSUE TITLE
homeassistant const change

### ISSUE THREAD

**Issue by Palmdale95** [mauro-midolo/homeassistant_electrolux_status#155]
Hi there,

in the future there will be a change to the logic in homeassitant so this message was initilized in the protocoll:

Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 9. Januar 2024 um 20:19:36 (3 occurrences)
Last logged: 9. Januar 2024 um 20:19:36

TIME_MINUTES was used from electrolux_status, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please create a bug report at https://github.com/mauro-midolo/homeassistant_electrolux_status/issues
TEMP_CELSIUS was used from electrolux_status, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/mauro-midolo/homeassistant_electrolux_status/issues
POWER_WATT was used from electrolux_status, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/mauro-midolo/homeassistant_electrolux_status/issues

Is this already been taken care of in the developing actions in the future? Otherwise it would be nice to include now :-)

**Comment by mauro-midolo** [comment]
Please upgrade to v5.0.0

**Comment by Palmdale95** [comment]
Looks like it solved it. Thanks a lot.
