### ISSUE TITLE
Is this integration EOL?

### ISSUE THREAD

**Issue by cloudbr34k84** [mauro-midolo/homeassistant_electrolux_status#156]
Im very grateful for anyone who can do all this awesome coding, but just wondering if this integration is now fully broke with no update  or fix?

**Comment by ilgigante77** [comment]
I would like to have updates too. My integration won't connect anymore to my account.

**Comment by Memphius** [comment]
It looks like some API issue since the 'original app' got shutdown.

**Comment by abdonkov** [comment]
The main dependency of this project, the pyelectroluxconnect repo has been archived as Electrolux / AEG has deprecated the old apps and API, which no longer works.

So, yes this is definitely EOL.

**Comment by mauro-midolo** [comment]
Please, refer to the ticket #159 for all the details regarding the disruption of integration caused by the change in Electrolux server APIs
