### ISSUE TITLE
AEG Oven BPK748280M "Time To End" 

### ISSUE THREAD

**Issue by Kaspermaat** [mauro-midolo/homeassistant_electrolux_status#16]
Hi There,

Really nice work, I just tested the integration on our oven type: BPK748280M

Everything works except the "Time to End".

<img width="335" alt="Schermafbeelding 2022-04-10 om 14 30 59" src="https://user-images.githubusercontent.com/58333104/162618243-65fa80bd-4ae8-4dca-b26d-d62be6fbe949.png">
 
If i can be of any help, please let me know.

**Comment by tomeko12** [comment]
Hi @Kaspermaat 
Can You see "Time to end" in official mobile app? If Yes, could You send device state (method describred in #23)

**Comment by Kaspermaat** [comment]
Hi @tomeko12,
Job well done! I forgot to check everything after the update. Just checked and it is working as it should be.
Thanks for reaching out! The Oven BPK748280M can be added to working devices.
