### ISSUE TITLE
electrolux_status integration not ready yet; Retrying in background

### ISSUE THREAD

**Issue by cloudbr34k84** [mauro-midolo/homeassistant_electrolux_status#21]
I started getting this error. I have re tried a few times now, but still get this error, is anyone else?

I had it working since before the update for HA Core.

Also if you want to add this fridge
Fridge
EHE6799SA
```
Logger: homeassistant.config_entries
Source: config_entries.py:366
First occurred: 09:40:02 (1 occurrences)
Last logged: 09:40:02

Config entry 'cloudbr34k84@gmail.com' for electrolux_status integration not ready yet; Retrying in background
```

**Comment by henriklundqvist** [comment]
For me it works fine with 2022.4.2 with release v1.11.0

When i upgrade to v1.12.0 i get the same error message as you

**Comment by cloudbr34k84** [comment]
> For me it works fine with 2022.4.2 with release v1.11.0
> 
> When i upgrade to v1.12.0 i get the same error message as you

ok goo to know, hopefully will be looked in.

**Comment by tomeko12** [comment]
What's Your appliance PNC number?

**Comment by henriklundqvist** [comment]
I have 5 appliances:

922717218-21
923421285-21
911438427-01
916098764-00
914555460-01

**Comment by henriklundqvist** [comment]
Works perfect now with 1.12.1. Many thanks
