### ISSUE TITLE
Sensor & Ambient temperature 

### ISSUE THREAD

**Issue by henriklundqvist** [mauro-midolo/homeassistant_electrolux_status#23]
Hi,

I have a fridge (923421285) and a freezer (922717218) that has 2 entities (sensor temperature & ambient temperature) that only shows 0.0 °C but in reality and in the official app it states 5º for the fridge and -18° for the freezer.

Is this a feature that can be implemented?

Many thanks for a great integration, i have 5 Electrolux appliances and it makes my life so much easier.

Kind regards,
Henrik

**Comment by tomeko12** [comment]
Hi @henriklundqvist .
Could You paste here output of this Python code?
```python
import pyelectroluxconnect
ses = pyelectroluxconnect.Session("email", "password", region="EMEA")
ses.login()
appllist = ses.getAppliances()
print(appllist)
for appliance in appllist:
    print("- Profile:")
    print(ses.getApplianceProfile(appliance))
    print("- State:")
    print(ses.getApplianceState(appliance, rawOutput = False))
    print("- Raw State:")
    print(ses.getApplianceState(appliance, rawOutput = True))
```

**Comment by henriklundqvist** [comment]
Hi @tomeko12 

When using pyscript integration i get the below error, any suggestions?

Logger: custom_components.pyscript.file.elux
Source: custom_components/pyscript/global_ctx.py:337
Integration: Pyscript Python scripting ([documentation](https://github.com/custom-components/pyscript), [issues](https://github.com/custom-components/pyscript/issues))
First occurred: 19:22:25 (1 occurrences)
Last logged: 19:22:25

Exception in </config/pyscript/elux.py> line 3: ses.login() ^ RuntimeError: Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()` at custom_components/pyscript/eval.py, line 1906: return func(*args, **kwargs)

**Comment by tomeko12** [comment]
Do You have ability to test this code in normal Python installed on operating system (not inside HA integration)?

**Comment by henriklundqvist** [comment]
➜  electrolux_status python3 elux.py
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/elux.py", line 1, in <module>
    import pyelectroluxconnect
ModuleNotFoundError: No module named 'pyelectroluxconnect'


do i have the  script in the wrong folder?

**Comment by tomeko12** [comment]
Try install manually `pyelectroluxconnect`:
```bash
pip install pyelectroluxconnect
```

**Comment by henriklundqvist** [comment]
Worked perfect, thanks!

Here is the output

[output.txt](https://github.com/mauro-midolo/homeassistant_electrolux_status/files/8515615/output.txt)

**Comment by tomeko12** [comment]
Thanks. It's all? There's only Your Dishwasher state in output file.

**Comment by henriklundqvist** [comment]
Some user error on my side :) here is new output, sorry.

[output2.txt](https://github.com/mauro-midolo/homeassistant_electrolux_status/files/8515760/output2.txt)

**Comment by tomeko12** [comment]
Your fridge and freezer reports only TargetTemperature valuses other than 0: (5°C and -18°C). Other temperature sensors (AmbientTemperature, SensorTemperature, DefrostTemperature) returns value = 0.

**Comment by henriklundqvist** [comment]
Stupid question maybe but does that mean i cannot see if the temperature suddenly increases if the door is slighly open (and therefore doesnt alarm) on the fridge? or would the value change to value 1 since its not target temperature anymore? 

In the official app there is high temperature alarm. Is that something that can be implented in your integration?

Thank you so much for looking into this

**Comment by tomeko12** [comment]
Do You see in Your official mobile app, if temperature is increasing/decreasing?

In appliance's profile files, there's Appliance State value named: "Stopped/Alarm". This sensor is supported by this integration, maybe it meet Your requirements.

I see, that there's also Hacl4AlertEvent with allowed values like: "Door Alarm", "Temperature Alarm", etc... It's not supported by this integration, but if You getApplianceState with Python code above, when this alarm (or better, alarms) is enabled, then maybe someone write code that support it.

**Comment by henriklundqvist** [comment]
Not sure if i can see temp increase/decrease. I will experiment a bit on
that.

My appliance state value returns only value "on" maybe it will show
something else when there is actual alarm or do you mean that its something
that can be easily added by this integration?

**Comment by tomeko12** [comment]
"Appliance State" don't require any change. You should experiment with this.
