### ISSUE TITLE
Please update to use pyelectroluxconnect v0.1.5 with region change support

### ISSUE THREAD

**Issue by TheHomieFox** [mauro-midolo/homeassistant_electrolux_status#3]
Ciao @mauro-midolo 
May I ask to please update to use version 0.1.5 of pyelectroluxconnect which supports region selection? I'm keen to test the integration for my region APAC, and will report back.
Thanks!

**Comment by mauro-midolo** [comment]
Ciao @TheHomieFox ,

I just release a new version v1.3.0 that includes "Region" parameter.
Could you please test it and in case close this issue.

Thanks
Mauro

**Comment by TheHomieFox** [comment]
@mauro-midolo thank you. I tested it and unfortunately it did not work.
The integration asked me for credential details and region selection. Entered 'apac' on that field and submitted. Response was that the integration was successfully added.
But then the integration status is "Retrying setup" and logs show the following:

`WARNING (MainThread) [homeassistant.config_entries] Config entry 'XXXXXXXX@gmail.com' for electrolux_status integration not ready yet; Retrying in background`

Happy to further test and troubleshoot, but I'm not getting much from the logs. Is there a debug mode?

Thanks!

**Comment by jbergler** [comment]
This probably isn't much help, but I wanted to report that using the "apac" region works for me.

**Comment by TheHomieFox** [comment]
Hi @jbergler, could you please provide further details as to how you set it up?

**Comment by jbergler** [comment]
I didn't do anything special as far as I can tell, I simply typed "apac" into the region field when setting the integration up.

**Comment by TheHomieFox** [comment]
Thanks for that @jbergler. I tried reinstalling the repository and integration, also tested in a separate environment, all with the same error message. The integration accepts the credentials with no issues, but then it doesn't create any entities and it gets stuck in Retrying setup.

I enabled DEBUG level logging and I'm getting the following:

`2022-03-19 16:27:18 INFO (MainThread) [homeassistant.setup] Setting up electrolux_status
2022-03-19 16:27:18 INFO (MainThread) [homeassistant.setup] Setup of domain electrolux_status took 0.0 seconds
2022-03-19 16:27:21 DEBUG (MainThread) [custom_components.electrolux_status] Finished fetching electrolux_status data in 1.704 seconds (success: False)
2022-03-19 16:27:21 WARNING (MainThread) [homeassistant.config_entries] Config entry 'XXXXXXXXXX@gmail.com' for electrolux_status integration not ready yet; Retrying in background
2022-03-19 16:27:29 DEBUG (MainThread) [custom_components.electrolux_status] Finished fetching electrolux_status data in 1.883 seconds (success: False)`

And then it just keeps repeating:

`2022-03-19 16:27:42 DEBUG (MainThread) [custom_components.electrolux_status] Finished fetching electrolux_status data in 1.647 seconds (success: False)
2022-03-19 16:28:04 DEBUG (MainThread) [custom_components.electrolux_status] Finished fetching electrolux_status data in 1.125 seconds (success: False)
2022-03-19 16:28:46 DEBUG (MainThread) [custom_components.electrolux_status] Finished fetching electrolux_status data in 1.070 seconds (success: False)`

**Comment by mauro-midolo** [comment]
Ciao @TheHomieFox,
I close this task because the region parameter was integrated correctly.
I think you have a unknown problem. 
If it not fix by v1.6.0 version, open a new one with more details

**Comment by TheHomieFox** [comment]
Ciao @mauro-midolo. 

All good with closing it.

I did more testing and can confirm the issue is related to the appliance itself (Electrolux EHE6899 Fridge), when I remove the appliance the integration works well, and as soon as I add it it stops working. 

I'll try upcoming versions hoping this appliance will be supported.

Thanks again.
