### ISSUE TITLE
Time to end in hrs:min instead of min. 

### ISSUE THREAD

**Issue by dutch-erik** [mauro-midolo/homeassistant_electrolux_status#33]
Dryer: Is it possible to change Time to End in hrs:min instead of minutes?
Example: Time to End: 140 min --> Time to End: 1:20 hr/min 

Thanks! 

Using integration for AEG 9000 serie 3D Fiber Pro (T9DEN87CC)

**Comment by mauro-midolo** [comment]
Hello @dutch-erik,
The library is integrated with Home Assistant passing the unit of measurement (minutes),
your request must be made to the Home Assistant team because is a view feature.
