### ISSUE TITLE
Token probably expired, trying to get new one

### ISSUE THREAD

**Issue by dutch-erik** [mauro-midolo/homeassistant_electrolux_status#34]
Receiving both below ERROR/WARNING log messages.
How can I get a new token? Have been trying to remove and install integration, but didn't help.

```
Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:687
First occurred: 09:25:46 (1 occurrences)
Last logged: 09:25:46

Token probably expired, trying to get new one.
```

```
Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:642
First occurred: 14:52:22 (4 occurrences)
Last logged: 14:53:55

Request error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by RayRent** [comment]
Reporting the same issue with a T9DEN87CC

Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend-versie: 20221010.0 - latest

**Comment by dutch-erik** [comment]
Does it matter to which value you change it?
Or just change to something and save it?

**Comment by RayRent** [comment]
It's now on 30 sec

**Comment by tomeko12** [comment]
New release of pyelectroluxconnect 0.3.7 could fix this problem

**Comment by RayRent** [comment]
Thanks, pyelectroluxconnect 0.3.5 is part of your v1.15.0 release?
