### ISSUE TITLE
Question about Service

### ISSUE THREAD

**Issue by Kaspermaat** [mauro-midolo/homeassistant_electrolux_status#38]
Hi,

I was wondering, is there a way to control the AEG device? We have got a oven and we can control it via the App of AEG. So far I can't find a Service in HASS is that correct? I can turn on the Oven with the button, but can't set the temperature to 200 for example.

Thanks!

**Comment by TripitonPT** [comment]
I have an AEG FSE74718P dishwhaserthst I used to control with the app "AEG Kitchen" and this integration works perfectly with it.

**Comment by Kaspermaat** [comment]
I is indeed working with the App of AEG. But I was wondering if you can control your dishwasher with HASS as well? Can you choose a washing program for example with Home Assistant?

**Comment by tomeko12** [comment]
@Kaspermaat, what is Your oven PNC number?

**Comment by Kaspermaat** [comment]
The oven is an AEG BPK748280M

**Comment by kentora** [comment]
It seems that it might be possible, on my oven the target temperature seems to be read/write, as per json output:
`   "OV1:0x0432":{
      "data_format":"struct",
      "name":"TargetTemperature",
      "type":"Container",
      "path":"/HaclV4/OV1",
      "visibility":"visible",
      "access":"readwrite",
      "source":"OV1",
      "nameTransl":"Temperature",
      "container":[
         {
            "1":{
               "data_format":"int16",
               "name":"Coefficient",
               "type":"Field",
               "visibility":"visible",
               "access":"readwrite",
               "nameTransl":""
            },
            "3":{
               "data_format":"int8",
               "increment":"0",
               "max_value":"0",
               "min_value":"0",
               "name":"Exponent",
               "type":"Field",
               "visibility":"visible",
               "access":"readwrite",
               "nameTransl":""
            },
            "0":{
               "data_format":"uint8",
               "increment":"0",
               "max_value":"0",
               "min_value":"0",
               "name":"Unit",
               "type":"Field",
               "visibility":"visible",
               "access":"readwrite",
               "steps":{
                  "0":{
                     "transl":"Celsius",
                     "key":"CELSIUS"
                  }
               },
               "nameTransl":""
            }
         }
      ]
   },`

I have yet to fully understand the structure of plugins, but might try and add this at some point in time

**Comment by tomeko12** [comment]
@kentora, Can You try some commands? I don't have oven, so i can't check, if this working:
For target temp (150°C) try:
ses.setHacl(appliance, "0x0432", [{"1":150},{"3":0},{"0":0}], "OV1")

For rinsing try to use command: 
ses.setHacl(appliance, "0x1440", "CDC1", "OV1")

**Comment by kentora** [comment]
@tomeko12 Temperature is working just fine, changing process is not. I will continue to play around a bit with process.

**Comment by kentora** [comment]
I got process selection to work, but that required changes in the underlying library, where I have opened an issue for this (Linked above)

**Comment by tomeko12** [comment]
Could You make some tests with curl, and check proper values to send for process change?
1. Get session_token (replace :EMAIL: and :PASSWORD: with Your credentials):
```shell
curl --request POST \
  --insecure \
  --url https://api.emea.ecp.electrolux.com/authentication/authenticate \
  --header 'Authorization: Basic dXNlcjpwYXNz' \
  --header 'Content-Type: application/json' \
  --header 'x-api-key: 714fc3c7-ad68-4c2f-9a1a-b3dbe1c8bb35' \
  --header 'x-ibm-client-id: 714fc3c7-ad68-4c2f-9a1a-b3dbe1c8bb35' \
  --data $'{
	"brand":"Electrolux",
	"country":"GB",
	"fields":{},
	"deviceId":"012345678901234567890012345678900123456789001234567890012345678900123456",
	"username":":EMAIL:",
	"password":":PASSWORD:"
}'
```

2. Get appliances list (replace :EMAIL: with Your email, :SESSION_KEY: with sessionKey value):
```shell
curl --request GET \
  --insecure \
  --url https://api.emea.ecp.electrolux.com/user-appliance-reg/users/:EMAIL:/appliances \
  --header 'session_token: :SESSION_KEY:' \
  --header 'x-ibm-client-id: 714fc3c7-ad68-4c2f-9a1a-b3dbe1c8bb35'
```

3. Send command to appliance (replace :PNC:, :ELC:, :SN:, :MAC: with values from appliances list, :SESSION_KEY: with sessionKey value):
```shell
curl --request POST \
  --insecure \
  --url 'https://api.emea.ecp.electrolux.com/commander/remote/sendjson?pnc=:PNC:&elc=:ELC:&sn=:SN:&mac=:MAC:' \
  --header 'Content-Type: application/json' \
  --header 'session_token: :SESSION_KEY:' \
  --header 'x-ibm-client-id: 714fc3c7-ad68-4c2f-9a1a-b3dbe1c8bb35' \
  --data '{
	"components": [{"name": "1440", "value": "CDC1"}], 
	"destination": "OV1", 
	"operationMode": "EXE", 
	"source": "RP1", 
	"timestamp": "1672416228", 
	"version": "ad"
}'
```
Try to set proper "value", that chenge setting in appliance.

**Comment by hugo-leij** [comment]
@tomeko12  @kentora 
I'm looking to change the temperature in my oven via HA. Did you manage that?
