### ISSUE TITLE
Lots of "No model name in profile file" lookups, possibly overloading electrolux?

### ISSUE THREAD

**Issue by LordMike** [mauro-midolo/homeassistant_electrolux_status#42]
I'm seeing a bunch of these logs:

```
2022-10-21 14:59:28.935 INFO (SyncWorker_5) [pyelectroluxconnect.Session] No model name in profile file, try to find in other sites
2022-10-21 14:59:28.935 INFO (SyncWorker_5) [pyelectroluxconnect.Session] Trying to get model 916098764_00 info from https://www.electrolux-ui.com/ website
```

Is a request made on _each_ log entry?

If so - that's quite a lot of lookups. Is there any way to cache the results or fill out this "profile"? 

![image](https://user-images.githubusercontent.com/1027111/197203453-2e49d4fb-7b47-4bf2-a491-3a3bf7260d43.png)

**Comment by LordMike** [comment]
I've looked at some code and found _some_ files that are written / read from disk. I can also see these files, so it's not a permissions issue if those files are used for this caching.

It's a bit inconvenient, because these files are written to the Home directory, which in my case is `/root/`. I f.ex. have: 

```
/root/916098764_00_00.zip
/root/914555442_02_00.zip
```

But apparently these are still not enough to prevent new requests for, I assume, the same information.

**Comment by LordMike** [comment]
@mauro-midolo `pyelectroluxconnect` has been updated to 0.3.5, which adds caching of these informations.

**Comment by mauro-midolo** [comment]
I Just update the applicazion with the new library version,
You can update to v1.15.0

**Comment by LordMike** [comment]
Updated, logs indicate no requests are made after the initial ones.
