### ISSUE TITLE
Error EPC0105 - Data: Session key not found

### ISSUE THREAD

**Issue by Rikkie80** [mauro-midolo/homeassistant_electrolux_status#45]
Since a couple of days I get the following error. I don't see progress and connection seems to get lost every minute.

```
Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:199
First occurred: 19:47:38 (1 occurrences)
Last logged: 19:47:38

Invalid response, status code: ECP0105 - Data: Session key not found
```

I have 2 devices integrated which worked perfectly before:

- Washing machine: L7FENQ96
- Tumble Dryer: T9DEN87CC

I'm on the latest HA release (2022.12.7)

**Comment by tomeko12** [comment]
Try update pyelectoluxconnect to 0.3.8 in integration manifest file

**Comment by mauro-midolo** [comment]
I created new version with 0.3.8
