### ISSUE TITLE
Unable to connect to AEG kitchen

### ISSUE THREAD

**Issue by glenndehaan** [mauro-midolo/homeassistant_electrolux_status#47]
Hi i'm trying to connect to an AEG kitchen account but it seems it does not work. I live in The Netherlands and tried all regions within HA but none will work. I end up with the following message in the logs:

```
Unable to get session token: No Consumer with this email: glenn@dehaan.cloud

Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/config_flow.py", line 84, in _test_credentials
    await self.hass.async_add_executor_job(client.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 797, in login
    self._createToken()
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 155, in _createToken
    raise Error(f'Unable to get session token: {loginResp["message"]}')
pyelectroluxconnect.Session.Error: Unable to get session token: No Consumer with this email: glenn@dehaan.cloud
```

I verified the account details but they are fine. I even logged out my app and relogged in with the account to verify and it works fine in the app. Do you have a any idea what could be the problem here?

**Comment by kentora** [comment]
I've got connection to AEG kitchen just fine - did you remember to select the correct region (EMEA)?

**Comment by glenndehaan** [comment]
Hi yeah I tried all regions just to be sure. But non of them work including emea. This is also the default selected within HA when you add the integration.

**Comment by glenndehaan** [comment]
One addition these messages are also logged:

```
Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:199
First occurred: 11:18:27 (11 occurrences)
Last logged: 23:11:02

Unable to get device configuration file.
Invalid response, status code: ECP0105 - Data: Session key not found
```
Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:805
First occurred: 11:18:27 (13 occurrences)
Last logged: 23:11:02

Unable to get device configuration file.
Unable to get session token: No Consumer with this email: glenn@dehaan.cloud
Login error: authentication_failed
Login error: User is not valid: glenn@dehaan.cloud
```

**Comment by glenndehaan** [comment]
Looks like it's connected to #45

**Comment by kentora** [comment]
Hmm, maybe its connected to the newer versions of Home Assistant - I'm still on an older version.

**Comment by glenndehaan** [comment]
That could be i'm running HA 2022.12.8 and Integration version 1.15.0

**Comment by kentora** [comment]
Hmm, seems that the underlying library updated it's session key handling since the version used in this integration. Would it be possible for you to try updating the library "pyelectroluxconnect" to version 0.3.7 and check if it fixes the error?
I believe it could, since they added code to handle this specific error code, but have no means of testing since mine already works.

**Comment by glenndehaan** [comment]
Thank you for the suggestion I just tried this by changing the manifest.json on my HA machine and then restarting but it seems the integration needs changes to make this work since I now get this exception:

```
This error originated from a custom integration.

Logger: custom_components.electrolux_status.config_flow
Source: custom_components/electrolux_status/config_flow.py:84
Integration: Electrolux Care Integration (documentation, issues)
First occurred: 22:25:28 (2 occurrences)
Last logged: 22:25:39

'Exception' object has no attribute 'text'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 809, in login
    self._getAppliancesList()
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 193, in _getAppliancesList
    applianceProfile = self._getApplianceConfiguration(self._applianceIndex[device["appliance_id"]]["pnc"],
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 262, in _getApplianceConfiguration
    raise Exception("Unable to get device configuration file.")
Exception: Unable to get device configuration file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/config_flow.py", line 84, in _test_credentials
    await self.hass.async_add_executor_job(client.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 811, in login
    raise Exception(_LOGGER.error(f"Error while get Appliances list: {ErrorArg.text}")) from None
AttributeError: 'Exception' object has no attribute 'text'
```

**Comment by tomeko12** [comment]
Try update pyelectroluxconnect to 0.3.8
`No Consumer with this email: glenn@dehaan.cloud` - this message is generated when login/password is invalid (in APAC region). What mobile app have you used to appliance registration?

**Comment by glenndehaan** [comment]
I have changed the manifest to version 0.3.8 but now the config flow won't load anymore. Please see attached screenshots:

<img width="533" alt="Schermafbeelding 2022-12-28 om 22 00 44" src="https://user-images.githubusercontent.com/7496187/209871694-1d19e9bf-10e7-44fd-92d1-f9ebf8c8460e.png">
<img width="795" alt="Schermafbeelding 2022-12-28 om 22 01 06" src="https://user-images.githubusercontent.com/7496187/209871697-2dd23449-fb3b-4e5e-acc3-6bdcb991068c.png">

To clarify i'm using the following app: https://play.google.com/store/apps/details?id=com.aeg.myaeg.taste&hl=nl&gl=US

**Comment by glenndehaan** [comment]
Ah maybe this helps a bit more. This was logged inside the system logs:

```
Logger: homeassistant.config_entries
Source: config_entries.py:834
First occurred: 22:00:22 (2 occurrences)
Last logged: 22:00:32

Error occurred loading configuration flow for integration electrolux_status: cannot import name 'RequestError' from 'pyelectroluxconnect.Session' (/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py)
```

**Comment by tomeko12** [comment]
Try 0.3.9

**Comment by glenndehaan** [comment]
Oke the config flow works again, but i'm still not able to get it added. I do see new error messages inside the logs:

```
Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:277
First occurred: 22:46:43 (1 occurrences)
Last logged: 22:46:43

Exception in _getApplianceConfiguration(944066845,00,11614262): Unable to get device configuration file.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 275, in _getApplianceConfiguration
    raise Exception("Unable to get device configuration file.")
Exception: Unable to get device configuration file.
```

```
Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:211
First occurred: 22:46:43 (1 occurrences)
Last logged: 22:46:43

Exception in _getAppliancesList: Unable to get device configuration file.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 200, in _getAppliancesList
    applianceProfile = self._getApplianceConfiguration(self._applianceIndex[device["appliance_id"]]["pnc"],
  File "/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 278, in _getApplianceConfiguration
    raise Error(err) from None
pyelectroluxconnect.Session.Error: Unable to get device configuration file.
```

```
Logger: pyelectroluxconnect.Session
Source: /usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py:895
First occurred: 22:45:54 (2 occurrences)
Last logged: 22:46:43

Invalid username or password (AER0802)
Unable to get device configuration file.
```

Now I did verify the email adres and password and both are correct and I am using the EMEA region within the config flow

**Comment by glenndehaan** [comment]
@tomeko12 It seems that with the latest v2.3.0 version (of this integration) my issues are resolved. Thank you for your time.

![image](https://user-images.githubusercontent.com/7496187/211827910-ee36ee3e-fabf-4d0e-8a68-ed1c32767b12.png)
