### ISSUE TITLE
Latest version error

### ISSUE THREAD

**Issue by apedance** [mauro-midolo/homeassistant_electrolux_status#49]
Logger: homeassistant.setup
Source: setup.py:210
First occurred: 00:26:21 (1 occurrences)
Last logged: 00:26:21

Setup failed for custom integration electrolux_status: Unable to import component: cannot import name 'RequestError' from 'pyelectroluxconnect.Session' (/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py)

**Comment by cloudbr34k84** [comment]
Same
Logger: homeassistant.setup
Source: setup.py:210
First occurred: 9:23:29 am (1 occurrences)
Last logged: 9:23:29 am

Setup failed for custom integration electrolux_status: Unable to import component: cannot import name 'RequestError' from 'pyelectroluxconnect.Session' (/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py)

**Comment by stefanraduionescu** [comment]
same error

Logger: homeassistant.setup
Source: setup.py:210
First occurred: 07:50:09 (1 occurrences)
Last logged: 07:50:09

Setup failed for custom integration electrolux_status: Unable to import component: cannot import name 'RequestError' from 'pyelectroluxconnect.Session' (/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py)

**Comment by wgumaa** [comment]
Same issue

**Comment by mauro-midolo** [comment]
Deleted v1.16.0
