### ISSUE TITLE
EOE8P19WX issue with v1.16.0

### ISSUE THREAD

**Issue by az-iot** [mauro-midolo/homeassistant_electrolux_status#50]
Hello,
Thank you for this great integration! I'm using it for the Oven ELECTROLUX EOE8P19WX for few months already but it stopped working after upgrading to the latest firmware. After downgrading to v1.15.1 everything is back to normal again.
Sheers

**Comment by stefanraduionescu** [comment]
Home Assistant 2022.12.8
AEG L9WBA61BC

After upgrading I got an error:

Setup failed for custom integration electrolux_status: Unable to import component: cannot import name 'RequestError' from 'pyelectroluxconnect.Session' 
(/usr/local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py)

**Comment by mauro-midolo** [comment]
Deleted v1.16.0
