### ISSUE TITLE
Not all states are in correct format

### ISSUE THREAD

**Issue by TorbenArentoft** [mauro-midolo/homeassistant_electrolux_status#6]
Some of the states are logged in a wrong format, and are as such not available in the History. It is, as of right now:
- Cycle Phase
- SSID
- Signal strenth

In history they appear as a graph with expected values between 0 and 1, but they are recorded as Text Strings in the database.
![Skærmbillede 2022-03-19 181508](https://user-images.githubusercontent.com/61244815/159131409-ec87ab76-b047-4cb3-9151-dca1cb97ef72.png)
![Skærmbillede 2022-03-19 181737](https://user-images.githubusercontent.com/61244815/159131411-dcd1116b-cb53-440d-8306-c7d23b33d83d.png)

(Furthermore Signal Strength should, by the way, perhaps be recorded as actual dB value, instead of the current Strings)

Other than that: Love this integration 👍

**Comment by mauro-midolo** [comment]
Ciao @TorbenArentoft,
I just fix this bug in v1.8.0.
I ask you to the the new version and in case close the issue.
(Remember you can see the correct values after the update, so apply a time filter to select only the history after update)

**Comment by TorbenArentoft** [comment]
Ciao Mauro,

It has indeed been fixed 👍
