### ISSUE TITLE
Error: parameter is read only

### ISSUE THREAD

**Issue by PCR-2020** [mauro-midolo/homeassistant_electrolux_status#60]
Hi,

Great to finally have an AEG Kitchen (Electrolux) integration. Installation went smooth (although a install via HACS button would make it even more easy) and my Dishwasher was immediately found (FSK73778P).

Status is given correctly (and updated fast) but I can't send commands. (Pause, resume, start stop are exposed). When I try to send a command I get:

Failed to call service/button press. Unable to set HACL 0x0403: Parameter is read only(based on profile file).

**Comment by tomeko12** [comment]
Hi. 
Commands in Your aplliance profile are exposed as read only. You can try update pyelectroluxconnect to 0.3.12 in manifest.json file, and check.

**Comment by PCR-2020** [comment]
Since the machine is capable of exact those commands via AEG app, and all commands gave back 0x0403, and not their own codes I suspected a bug.

And indeed 0.3.12 indeed fixed the issue. It now completely works, so you can add the dishwasher to the tested machines 😉  (with 0.3.12)
