### ISSUE TITLE
async_setup_platforms

### ISSUE THREAD

**Issue by coserotondo** [mauro-midolo/homeassistant_electrolux_status#70]
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for electrolux_status using this method at custom_components/electrolux_status/__init__.py, line 62: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by mauro-midolo** [comment]
Please, update to the new version v2.3.5.

**Comment by coserotondo** [comment]
Done, no more logs. Thanks!
