### ISSUE TITLE
Handler ElectroluxStatusFlowHandler doesn't support step reauth

### ISSUE THREAD

**Issue by coserotondo** [mauro-midolo/homeassistant_electrolux_status#79]
Hi,

This happens on HA start:

is an expected behaviour?

Logger: homeassistant
Source: data_entry_flow.py:330
First occurred: 10:26:55 (1 occurrences)
Last logged: 10:26:55

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 826, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 330, in _async_handle_step
    raise UnknownStep(
homeassistant.data_entry_flow.UnknownStep: Handler ElectroluxStatusFlowHandler doesn't support step reauth

**Comment by coserotondo** [comment]
![Screenshot 2023-02-27 at 10 33 01](https://user-images.githubusercontent.com/121899012/221526833-87b0b249-8690-430d-8eb7-7f50d2908e68.png)

**Comment by coserotondo** [comment]
Maybe it was a server error, I tried several times to reload integration and finally today it worked again.

**Comment by mauro-midolo** [comment]
@coserotondo please update to the last version on check

**Comment by EWK1** [comment]
I'm in the latest version. Had the same.
Deleted the integration in HA and trying to add again. Now it says username/password wrong, but credentials als correct and I can login with them om the AEG website.

**Comment by coserotondo** [comment]
> @coserotondo please update to the last version on check

It works fine
