### ISSUE TITLE
Lastest Update Error

### ISSUE THREAD

**Issue by cloudbr34k84** [mauro-midolo/homeassistant_electrolux_status#84]
Logger: custom_components.electrolux_status
Source: custom_components/electrolux_status/api.py:271
Integration: Electrolux Care Integration ([documentation](https://github.com/mauro-midolo/homeassistant_electrolux_status), [issues](https://github.com/mauro-midolo/homeassistant_electrolux_status/issues))
First occurred: 9:07:06 am (65 occurrences)
Last logged: 10:32:29 am

'list' object has no attribute 'items'
Traceback (most recent call last):
  File "/config/custom_components/electrolux_status/__init__.py", line 99, in _async_update_data
    app.setup(ElectroluxLibraryEntity(appliance_name, connection_state, appliance_state, appliance_profile))
  File "/config/custom_components/electrolux_status/api.py", line 271, in setup
    for key, command in data.commands_list(src).items():
AttributeError: 'list' object has no attribute 'items'

**Comment by mauro-midolo** [comment]
@cloudbr34k84, the problem should be fixed in v2.6.1

**Comment by cloudbr34k84** [comment]
Cheers mate! Great work

**Comment by cloudbr34k84** [comment]
@mauro-midolo do you think you will make this an official HA integration??
