### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by CGU1969** [mauro-midolo/homeassistant_electrolux_status#90]
After update to the last version 2.6.3 login doesn't work. 
I have change the Electrolux password, and don't working.

**Comment by syepes** [comment]
I also confirm, looks like they have changed something in the backend.
`Exception: Invalid API response: Unauthorized (401)` 

I am also getting the logging errors and I have just verified the credentials with the phone app

**Comment by MicheleMercuri** [comment]
logging errors me too.

**Comment by mauro-midolo** [comment]
Please, try to upgrade to v2.6.4

**Comment by CGU1969** [comment]
Now, in v2.6.4, the login it's working fine.
Thanks!

**Comment by wgumaa** [comment]
@CGU1969 you can close the issue now!
