### ISSUE TITLE
Latest version giving some issues! 

### ISSUE THREAD

**Issue by wgumaa** [mauro-midolo/homeassistant_electrolux_status#91]
Hi Mauro,  I have updated to the latest version and I am having issues. 

The integration stopped working and tried to reload it a few times and had the same issue. 

I updated the HACS integration, I uninstalled the integration and reinstalled.

Set up asks for username and password. I enter the same as my Electrolux Care app (That works) and it comes back with the wrong username/password. 

Any ideas?

**Comment by wgumaa** [comment]
Ok for us newbies, how would we update that in Home Assistant?

**Comment by mauro-midolo** [comment]
I just released the new versione that should be fix the problem.

**Comment by wgumaa** [comment]
I can confirm that its working now. Thanks!!!
